spring.application.name=portfolio_backend_spring_boot
server.port=8080
server.error.include-exception=false
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never

server.tomcat.basedir=.
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.directory=logs
server.tomcat.accesslog.pattern=%t "%r" %s 
server.tomcat.accesslog.prefix=access_log
server.tomcat.accesslog.suffix=.log

app.data.mongodb.host=localhost
app.data.mongodb.port=27017
app.data.mongodb.max-pool-size=10000
app.data.mongodb.database=personality
app.data.mongodb.collection=character_a
